# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            More Heat Than Light
tagline:          'A Jekyll theme'
description:      'Stumbles and falls through .NET Core and the modern web'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Johan Nyström'
  url:            https://spiderunicorn.github.io

paginate:         5

# Gems
gems: [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/SpiderUnicorn/spiderunicorn.github.io
